# Receipt QuickLook Plugin

This quick look plugin provides a way to visualize cryptographic receipt generated by the App Stores (iOS and OS X).
This is quite useful for iOS application as there is no way to visualize them on the device.

## How to build ?

Open the project with Xcode and hit the build button.
The project generates a QuickLook bundle named `ReceiptQuickLook.qlgenerator`.

## Installation

Once the QuickLook bundle is generated:

- copy it under the `~/Library/QuickLook/` folder for a user-wide use.
- copy it under the `/Library/QuickLook/` folder for a system-wide use. You may need to authenticate in order to copy the bundle.

Then, open a **Terminal** window and type `qlmanage -r` in order to rebuild the QuickLook plugin database.

## How to use ?

Like any other QuickLook plugin, go in the **Finder**, select a receipt file and press the `space` key.

## Inspecting iOS receipt

In order to inspect iOS receipt, you have to:

- Open the **Xcode** organizer window.
- Select the device where your application is installed, then the **Applications** item.
- Select the application and below the sandbox area, click on the download button.
  This will save a bundle with the `xcappdata` extension containing all the files from the application's sandbox.
- In the **Finder**, right-click on the sandbox bundle and select `Show Package Contents`.
- Go to the `AppData/StoreKit` folder and select the receipt file; press the `space` key.
- Et Voilà !

## License

The Receipt QuickLook Plugin is licensed under the GNU General Public License v3.
See <http://www.gnu.org/licenses/> for more details.
